### ISSUE TITLE
Performance characteristics

### ISSUE THREAD

**Issue by christophercliff** [wooorm/retext#27]
Any benchmarks or recommendations?

**Comment by wooorm** [comment]
Fast enough for what it does, in my opinion :wink:.

I used to keep benchmarks in here, but opted to remove them because they’re so widely dependent on the set-up, and also, retext doesn’t do much itself. What you probably want to benchmark is doing something with retext instead.

If you’re going to use retext to detect syllables, you will probably be faster off with another solution.
When doing multiple things, retext might just be faster than other solutions.
If you’re doing fancy stuff, the CST retext provides is very important, and retext is the only player in the field providing that (thus not benchmark-able).

**Comment by christophercliff** [comment]
Thanks for the info.
