### ISSUE TITLE
retext-knwl

### ISSUE THREAD

**Issue by FranzSkuffka** [wooorm/retext#28]
So there is this seemingly abandoned piece of software called [knwl.js](https://github.com/loadfive/Knwl.js). I am fairly unfamiliar with retext and it's ecosystem but still I was wondering if it might make sense to create a knwl-js plugin for retext. This would enable basic NER.

**Comment by wooorm** [comment]
Thanks for suggesting. It would be possible to create some tool like this for retext, but I'm not (no longer) interested in creating it. The reason being that retext's power comes from retext-equality, retext-simplify, spelling detection, and the like, rather than plain natural language processing.
The syntax tree format used internally is really useful for detecting patterns as seen in these plug-ins, and less so for phone numbers (which can be better found using a regex than a syntax tree).

Hope this helps!

**Comment by FranzSkuffka** [comment]
Thank you for the insight! What I gathered is that retext is a  completely different thing and NER is out of scope.

**Comment by wooorm** [comment]
Quite right!
